package cmc.mody.notification.domain;

public enum NotificationType {
    GROUP_JOINED,
    RECORD_REMINDER,
    COMMENT,
    STREAK,
    NUDGE,
    CHALLENGE,
    GROUP_MEMBER_JOINED,
    EXERCISE_REMINDER,
    MEAL_REMINDER,
    COMMENT_CREATED,
    GROUP_RECORD_STREAK_RISK,
    BUDDY_NUDGE,
    STEP_CHALLENGE_COMPLETED,
    WEEKLY_CHALLENGE_COMPLETED,
    DEV_TEST
}
